trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: 'New variable group 11-Sep'

steps:

# Build / Validate Static Application
- script: |
    echo "Building Static Application..."
    ls -la
  displayName: 'Build Static Application'

# Deploy to Azure Static Web Apps
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    output_location: ''
    azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
